---
# tasks file for wildfly
#
- name: Add wildfly admin user
  shell: "./add-user.sh -u {{ wildfly_admin_user }} -p {{ wildfly_admin_pass }} "
  args:
    chdir: "{{ install_location }}{{ wildfly_zip[:-4] }}/bin/"
  ignore_errors: yes
  changed_when: false

- name: Copy the init script to /etc/init.d/
  copy:
    src: "{{ install_location }}{{ wildfly_zip[:-4] }}/docs/contrib/scripts/init.d/{{ wildfly_service_script }}"
    dest: /etc/init.d/{{ service_name }}
    mode: 0755
    remote_src: yes

- name: reload daemon
  systemd:
    daemon_reload: yes

- name: copy the wildfly config to /etc/default/
  template:
    src: templates/{{ wildfly_service_conf }}
    dest: /etc/default/wildfly
    owner: "{{ system_user }}"
    group: "{{ system_user }}"

- name: copy the standalone xml config
  template:
    src: templates/{{ wildfly_host_config }}
    dest: "{{ wildfly_home }}/{{ wildfly_mode }}/configuration/{{ wildfly_host_config }}"
  notify: restart wildfly

- name: enable to run on system boot
  shell: chkconfig {{ service_name }} on
  ignore_errors: yes
  changed_when: False
  tags:
    - enable_to_run_on_system_boot
    - install_yml

- name: Start Wildfly
  service:
    name: "{{ service_name }}"
    state: started
