---
- name: copy java tar file
  unarchive:
    src: "{{ pkg_location }}/{{ java_zip }}"
    dest: "/opt/"
    creates: "/opt/jdk-14.0.2"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"

- name: add bin path to env
  template:
    src: templates/jdk14.sh
    dest: /etc/profile.d/

- name: source the new configs
  shell: "source /etc/profile.d/jdk14.sh"
  ignore_errors: yes
  changed_when: false
